"""
nak.agents.AgentCreator.agent -- creates new agents on disk after explicit confirmation.

Approved plan (#5): never writes without `await confirm(spec) == True`.

Flow:
    DecisionResult(action=CREATE_AGENT, agent_name="ExcelAgent", reason=..., confidence=...)
        │
        ▼
    AgentCreator.create(spec, confirm=async cb)  # cb: (DecisionResult)->bool
        │
        ├─ if not confirmed → return None, no side effects
        ├─ validate/slugify name, check not exists
        ├─ mkdir nak/agents/<Slug>/
        ├─ write __init__.py + agent.py from template (based on Example/base.py)
        ├─ update nak/agents/registry.json (JSON leader) via AgentRegistry
        ├─ mirror to Memory: brain.remember("Registered ExcelAgent: ...") (hybrid index, best-effort)
        └─ return Path

Safety:
- No overwrite: mkdir exist_ok=False, validate_agent_name, registry.exists guard
- All FS writes are atomic per-file; on failure, cleanup rmdir best-effort
- Memory mirror is best-effort (never fails creation if Mind down) — JSON remains source of truth
- allow_create flag defaults False in some call sites; here we enforce confirm() regardless
"""
from __future__ import annotations

import asyncio
import logging
import shutil
import textwrap
from pathlib import Path
from typing import Callable, Awaitable, Optional, Any, Dict

from nak.brain.client import Brain
from nak.utils.agent_registry import AgentRegistry, AgentMeta, slugify, validate_agent_name
from nak.agents.DecisionAgent.models import DecisionResult

logger = logging.getLogger("nak.agents.AgentCreator")


ConfirmFn = Callable[[DecisionResult], Awaitable[bool]]


_AGENT_INIT_TEMPLATE = '''"""nak.agents.{name} -- generated by AgentCreator (confirm-gated)."""
from .agent import Agent  # noqa: F401

__all__ = ["Agent"]
'''

_AGENT_PY_TEMPLATE = '''"""
nak.agents.{name}.agent -- generated skeleton (confirm-gated).

This agent proxies to NebulonMind via Brain, like Example/SimpleAgent.
Fill in domain logic; keep Mind-only (no direct openai client).

Usage:
    from nak.agents.{name}.agent import Agent
    from nak.brain import Brain
    agent = Agent(brain=Brain())
    reply = await agent.run("hello")  # or agent.run_sync("hello")
"""
from __future__ import annotations

import asyncio
from typing import Dict, Any, List, Optional

from nak.brain.client import Brain


class Agent:
    """{name} — handles: {reason}"""

    name = "{name}"

    def __init__(self, brain: Optional[Brain] = None, system_prompt: Optional[str] = None) -> None:
        self.brain = brain or Brain()
        self.system_prompt = system_prompt or "You are {name}, a helpful assistant for {reason_lower}."

    def run_sync(self, text: str, messages: Optional[List[Dict[str, str]]] = None, **kwargs: Any) -> Dict[str, Any]:
        if not text or not text.strip():
            raise ValueError("text must be non-empty")
        history = list(messages or [])
        if self.system_prompt and not any(m.get("role") == "system" for m in history):
            history = [{{"role": "system", "content": self.system_prompt}}] + history
        return self.brain.chat(text, messages=history or None, **kwargs)

    async def run(self, text: str, **kwargs: Any) -> Dict[str, Any]:
        return await asyncio.to_thread(self.run_sync, text, **kwargs)

    def chat(self, text: str, **kwargs: Any) -> str:
        data = self.run_sync(text, **kwargs)
        return str(data.get("answer") or data.get("content") or "")

    async def chat_async(self, text: str, **kwargs: Any) -> str:
        data = await self.run(text, **kwargs)
        return str(data.get("answer") or data.get("content") or "")
'''


class AgentCreator:
    """Creates new agents on disk. Confirm-gated, hybrid JSON+Memory."""

    name = "AgentCreator"

    def __init__(
        self,
        brain: Optional[Brain] = None,
        registry: Optional[AgentRegistry] = None,
        agents_root: Optional[Path] = None,
    ) -> None:
        self.brain = brain or Brain()
        self.registry = registry or AgentRegistry()
        # agents_root derived from registry if not given
        self.agents_root = Path(agents_root) if agents_root else self.registry.agents_root

    async def create(
        self,
        spec: DecisionResult,
        confirm: ConfirmFn,
        description: Optional[str] = None,
        capabilities: Optional[list] = None,
        template_vars: Optional[Dict[str, Any]] = None,
    ) -> Optional[Path]:
        """
        Create a new agent from a CREATE_AGENT DecisionResult, after confirmation.

        Args:
            spec: DecisionResult with action==CREATE_AGENT and agent_name
            confirm: async callable (DecisionResult)->bool — must return True to proceed
            description: override description (default spec.reason)
            capabilities: override capabilities list
            template_vars: extra vars for template rendering
        Returns:
            Path to created agent folder, or None if not created (not confirmed / not CREATE_AGENT)
        Raises:
            ValueError on invalid name
            FileExistsError if agent already exists (registry or disk)
        """
        if not isinstance(spec, DecisionResult):
            raise TypeError(f"spec must be DecisionResult, got {type(spec)}")
        if spec.action != "CREATE_AGENT":
            logger.info("AgentCreator.create: spec action is %s, not CREATE_AGENT — nothing to do", spec.action)
            return None
        if not spec.agent_name:
            raise ValueError("CREATE_AGENT spec must have agent_name")

        # 1. Confirm gate (#5) — never skip
        confirmed = await confirm(spec)
        if not confirmed:
            logger.info("AgentCreator.create: not confirmed for %s — aborting", spec.agent_name)
            return None

        slug = validate_agent_name(spec.agent_name)
        # Existence guards (both registry and disk)
        if self.registry.exists(slug):
            raise FileExistsError(f"agent {slug!r} already exists in registry.json")
        target = self.agents_root / slug
        if target.exists():
            raise FileExistsError(f"agent folder already exists: {target}")

        reason = (description or spec.reason or f"Handles {slug} tasks").strip()
        reason_lower = reason[:120].lower()
        caps = capabilities if capabilities is not None else list(spec.parameters.get("capabilities") or [])

        # 2. Create folder + files
        try:
            target.mkdir(parents=False, exist_ok=False)
            # __init__.py
            (target / "__init__.py").write_text(
                _AGENT_INIT_TEMPLATE.format(name=slug), encoding="utf-8"
            )
            # agent.py
            agent_py_content = _AGENT_PY_TEMPLATE.format(
                name=slug, reason=reason[:200].replace('"', "'"), reason_lower=reason_lower.replace('"', "'")
            )
            if template_vars:
                # simple extra rendering if needed
                for k, v in template_vars.items():
                    agent_py_content = agent_py_content.replace(f"{{{k}}}", str(v))
            (target / "agent.py").write_text(agent_py_content, encoding="utf-8")

            # 3. JSON leader — registry.json
            meta = AgentMeta(
                name=slug,
                description=reason[:300],
                path=f"nak/agents/{slug}",
                capabilities=caps,
                created_via="agent_creator",
                version="0.1.0",
            )
            self.registry.register(meta)

            # 4. Memory index — best-effort mirror to NebulonMind
            try:
                memory_text = f"Registered agent {slug}: {reason}. Capabilities: {', '.join(caps) if caps else 'general'}. Path: nak/agents/{slug}"
                # Use to_thread for sync brain.remember
                await asyncio.to_thread(
                    self.brain.remember,
                    memory_text,
                    category="agent_registry",
                    memory_type="knowledge",
                )
                logger.info("AgentCreator: mirrored %s to Memory", slug)
            except Exception as exc:
                # Never fail creation because Memory is down — JSON is leader
                logger.warning("AgentCreator: memory mirror failed for %s: %s (JSON leader preserved)", slug, exc)

            logger.info("AgentCreator: created %s at %s", slug, target)
            return target

        except Exception:
            # Cleanup on failure: try to remove partially created folder
            if target.exists():
                try:
                    # only remove if we just created it and it has at most 2 files
                    files = list(target.iterdir())
                    if len(files) <= 3:
                        shutil.rmtree(target, ignore_errors=True)
                        # also rollback registry if we already registered
                        try:
                            self.registry.remove(slug)
                        except Exception:
                            pass
                except Exception:
                    pass
            raise

    # -- sync convenience ------------------------------------------------------

    def create_sync(
        self,
        spec: DecisionResult,
        confirm_sync: Callable[[DecisionResult], bool],
        **kwargs,
    ) -> Optional[Path]:
        """Sync wrapper for create() when you have a sync confirm callback."""

        async def _async_confirm(s: DecisionResult) -> bool:
            return confirm_sync(s)

        return asyncio.run(self.create(spec, _async_confirm, **kwargs))
