"""
nak.agents.AgentCreator.agent -- creates new agents on disk after explicit confirmation.

Approved plan (#5): never writes without `await confirm(spec) == True`.

Flow:
    DecisionResult(action=CREATE_AGENT, agent_name="ExcelAgent", reason=..., confidence=...)
        │
        ▼
    AgentCreator.create(spec, confirm=async cb)  # cb: (DecisionResult)->bool
        │
        ├─ if not confirmed → return None, no side effects
        ├─ validate/slugify name, check not exists
        ├─ mkdir nak/agents/<Slug>/
        ├─ write __init__.py + agent.py from template (based on Example/base.py)
        ├─ update nak/agents/registry.json (JSON leader) via AgentRegistry
        ├─ mirror to Memory: brain.remember("Registered ExcelAgent: ...") (hybrid index, best-effort)
        └─ return Path

Safety:
- No overwrite: mkdir exist_ok=False, validate_agent_name, registry.exists guard
- All FS writes are atomic per-file; on failure, cleanup rmdir best-effort
- Memory mirror is best-effort (never fails creation if Mind down) — JSON remains source of truth
- allow_create flag defaults False in some call sites; here we enforce confirm() regardless
"""
from __future__ import annotations

import asyncio
import logging
import shutil
import textwrap
from pathlib import Path
from typing import Callable, Awaitable, Optional, Any, Dict

from nak.brain.client import Brain
from nak.utils.agent_registry import AgentRegistry, AgentMeta, slugify, validate_agent_name
from nak.agents.DecisionAgent.models import DecisionResult

logger = logging.getLogger("nak.agents.AgentCreator")


ConfirmFn = Callable[[DecisionResult], Awaitable[bool]]


_AGENT_INIT_TEMPLATE = '''"""nak.agents.{name} -- generated by AgentCreator (confirm-gated)."""
from .agent import Agent  # noqa: F401

__all__ = ["Agent"]
'''

_AGENT_PY_TEMPLATE = '''"""
nak.agents.{name}.agent -- generated skeleton (confirm-gated).

This agent proxies to NebulonMind via Brain, like Example/SimpleAgent.
Fill in domain logic; keep Mind-only (no direct openai client).

Usage:
    from nak.agents.{name}.agent import Agent
    from nak.brain import Brain
    agent = Agent(brain=Brain())
    reply = await agent.run("hello")  # or agent.run_sync("hello")
"""
from __future__ import annotations

import asyncio
import json
from typing import Dict, Any, List, Optional

from nak.brain.client import Brain
from nak.plugins import PLUGIN_TOOLS, execute_plugin
from nak.utils.config import load_config


def _parse_step_answer(raw):
    """Mind reply -> answer-step or tool-step. Unparseable replies become final answers."""
    answer = ""
    if isinstance(raw, dict):
        answer = str(raw.get("answer") or raw.get("content") or raw.get("text") or "")
    else:
        answer = str(raw)
    text = answer.strip()
    data = None
    try:
        data = json.loads(text)
    except (ValueError, TypeError):
        # brace-free fallback for markdown-wrapped JSON (no regex: braces
        # would need escaping in this .format() template)
        start, end = text.find("{{"), text.rfind("}}")
        if 0 <= start < end:
            try:
                data = json.loads(text[start:end + 1])
            except (ValueError, TypeError):
                data = None
    if isinstance(data, dict):
        if "answer" in data and "tool" not in data:
            return {{"kind": "answer", "text": str(data["answer"]) }}
        if "tool" in data:
            args = data.get("arguments") or {{}}
            if isinstance(args, str):
                try:
                    args = json.loads(args)
                except (ValueError, TypeError):
                    args = {{}}
            if not isinstance(args, dict):
                args = {{}}
            return {{"kind": "tool", "name": str(data["tool"]), "args": args}}
    return {{"kind": "answer", "text": answer}}


class Agent:
    """{name} — handles: {reason}"""

    name = "{name}"

    def __init__(self, brain: Optional[Brain] = None, system_prompt: Optional[str] = None) -> None:
        self.brain = brain or Brain()
        # NOTE: NebulonMind /agent/chat accepts only roles user/assistant/tool
        # (no "system"). role_hint + custom_instructions travel as plain
        # context prefixed to the user text — never as a message.
        default_hint = "You are {name}, a helpful assistant for {reason_lower}."
        self.role_hint = system_prompt if system_prompt is not None else default_hint
        self.custom_instructions = "{{custom_instructions}}"

    def _mind_step(self, prompt, messages, session_id):
        """One Mind reasoning step (overridable in tests without network)."""
        return self.brain.chat(prompt, messages=messages or None, session_id=session_id)

    def run_sync(self, text: str, messages: Optional[List[Dict[str, str]]] = None, **kwargs: Any) -> Dict[str, Any]:
        if not text or not text.strip():
            raise ValueError("text must be non-empty")
        context = " ".join(
            p.strip() for p in (self.role_hint, self.custom_instructions) if p and p.strip()
        ).strip()
        # NOTE: doubled braces below - this is a format template, so they
        # render as single braces in the generated agent file.
        effective = f"Agent context: {{context}}\\nUser request: {{text.strip()}}" if context else text.strip()
        # Only forward user/assistant/tool roles — Mind rejects "system".
        history = [m for m in (messages or []) if m.get("role") in ("user", "assistant", "tool")]
        from nak.plugins.tool.policy import reset_tool_once, approve_tool_use
        from nak.utils.config import load_config
        try:
            max_turns = max(1, load_config().policy_max_turns)
        except Exception:
            max_turns = 6
        reset_tool_once()
        session_id = kwargs.get("session_id")
        tool_brief = "; ".join(
            s["function"]["name"] + ": " + s["function"].get("description", "")[:80] for s in PLUGIN_TOOLS
        )
        transcript = [{{"role": "user", "content": effective}}]
        last_text, turns, steps = "", 0, []
        for _ in range(max_turns):
            turns += 1
            step_prompt = (
                "Reply with ONLY JSON - either " +
                '{{"tool": "<name>", "arguments": {{...}}}}' +
                " to use one tool, or " +
                '{{"answer": "..."}}' +
                " when done. No other text.\\n" +
                "Available tools: " + tool_brief + "\\n" +
                "History so far:\\n" + json.dumps(transcript[-10:], ensure_ascii=False)[:6000]
            )
            try:
                raw = self._mind_step(step_prompt, (history + transcript)[-12:] or None, session_id)
            except Exception as exc:
                last_text = f"[brain error: {{exc}}]"
                break
            step = _parse_step_answer(raw)
            if step["kind"] == "answer":
                last_text = step["text"]
                break
            tname, targs = step["name"], step["args"]
            if approve_tool_use(tname, targs):
                try:
                    result = execute_plugin(self.brain, tname, targs)
                    # executors answer errors as JSON instead of raising, so
                    # success must be read from the result payload itself.
                    try:
                        rok = "error" not in json.loads(result)
                    except (ValueError, TypeError):
                        rok = True
                    steps.append({{"tool": tname, "ok": rok}})
                except Exception as exc:
                    result = json.dumps({{"error": str(exc)[:500]}})
                    steps.append({{"tool": tname, "ok": False}})
            else:
                result = json.dumps({{"error": f"tool {{tname!r}} use denied (policy/user)"}})
                steps.append({{"tool": tname, "ok": False, "denied": True}})
            transcript.append({{"role": "assistant",
                               "content": json.dumps({{"tool": tname, "arguments": targs}}, ensure_ascii=False)}})
            transcript.append({{"role": "tool", "content": result}})
        return {{"answer": last_text or "(no answer after tool loop)", "turns": turns,
                "steps": steps, "agent": self.name}}

    async def run(self, text: str, **kwargs: Any) -> Dict[str, Any]:
        return await asyncio.to_thread(self.run_sync, text, **kwargs)

    def chat(self, text: str, **kwargs: Any) -> str:
        data = self.run_sync(text, **kwargs)
        return str(data.get("answer") or data.get("content") or "")

    async def chat_async(self, text: str, **kwargs: Any) -> str:
        data = await self.run(text, **kwargs)
        return str(data.get("answer") or data.get("content") or "")
'''


class AgentCreator:
    """Creates new agents on disk. Confirm-gated, hybrid JSON+Memory."""

    name = "AgentCreator"

    def __init__(
        self,
        brain: Optional[Brain] = None,
        registry: Optional[AgentRegistry] = None,
        agents_root: Optional[Path] = None,
    ) -> None:
        self.brain = brain or Brain()
        self.registry = registry or AgentRegistry()
        # agents_root derived from registry if not given
        self.agents_root = Path(agents_root) if agents_root else self.registry.agents_root

    async def create(
        self,
        spec: DecisionResult,
        confirm: ConfirmFn,
        description: Optional[str] = None,
        capabilities: Optional[list] = None,
        template_vars: Optional[Dict[str, Any]] = None,
    ) -> Optional[Path]:
        """
        Create a new agent from a CREATE_AGENT DecisionResult, after confirmation.

        Args:
            spec: DecisionResult with action==CREATE_AGENT and agent_name
            confirm: async callable (DecisionResult)->bool — must return True to proceed
            description: override description (default spec.reason)
            capabilities: override capabilities list
            template_vars: extra vars for template rendering
        Returns:
            Path to created agent folder, or None if not created (not confirmed / not CREATE_AGENT)
        Raises:
            ValueError on invalid name
            FileExistsError if agent already exists (registry or disk)
        """
        if not isinstance(spec, DecisionResult):
            raise TypeError(f"spec must be DecisionResult, got {type(spec)}")
        if spec.action != "CREATE_AGENT":
            logger.info("AgentCreator.create: spec action is %s, not CREATE_AGENT — nothing to do", spec.action)
            return None
        if not spec.agent_name:
            raise ValueError("CREATE_AGENT spec must have agent_name")

        # 1. Confirm gate (#5) — never skip
        confirmed = await confirm(spec)
        if not confirmed:
            logger.info("AgentCreator.create: not confirmed for %s — aborting", spec.agent_name)
            return None

        slug = validate_agent_name(spec.agent_name)
        # Existence guards (both registry and disk)
        if self.registry.exists(slug):
            raise FileExistsError(f"agent {slug!r} already exists in registry.json")
        target = self.agents_root / slug
        if target.exists():
            raise FileExistsError(f"agent folder already exists: {target}")

        reason = (description or spec.reason or f"Handles {slug} tasks").strip()
        reason_lower = reason[:120].lower()
        caps = capabilities if capabilities is not None else list(spec.parameters.get("capabilities") or [])

        # 2. Create folder + files
        try:
            target.mkdir(parents=False, exist_ok=False)
            # __init__.py
            (target / "__init__.py").write_text(
                _AGENT_INIT_TEMPLATE.format(name=slug), encoding="utf-8"
            )
            # agent.py (brace-safe: user text must not break str.format;
            # single-line escaped: generated code must stay valid Python)
            def _fmt(s: str) -> str:
                return s.replace("{", "{{").replace("}", "}}").replace('"', "'")

            def _one_line(s: str) -> str:
                return " ".join(str(s).replace("\\", "\\\\").replace('"', "'").split())

            agent_py_content = _AGENT_PY_TEMPLATE.format(
                name=slug, reason=_fmt(reason[:200]), reason_lower=_fmt(reason_lower)
            )
            tvars = dict(template_vars or {})
            tvars.setdefault("custom_instructions", "")
            for k, v in tvars.items():
                agent_py_content = agent_py_content.replace(f"{{{k}}}", _one_line(v))
            (target / "agent.py").write_text(agent_py_content, encoding="utf-8")

            # 3. JSON leader — registry.json
            meta = AgentMeta(
                name=slug,
                description=reason[:300],
                path=f"nak/agents/{slug}",
                capabilities=caps,
                created_via="agent_creator",
                version="0.1.0",
            )
            self.registry.register(meta)

            # 4. Memory index — best-effort mirror to NebulonMind
            try:
                memory_text = f"Registered agent {slug}: {reason}. Capabilities: {', '.join(caps) if caps else 'general'}. Path: nak/agents/{slug}"
                # Use to_thread for sync brain.remember
                await asyncio.to_thread(
                    self.brain.remember,
                    memory_text,
                    category="agent_registry",
                    memory_type="knowledge",
                )
                logger.info("AgentCreator: mirrored %s to Memory", slug)
            except Exception as exc:
                # Never fail creation because Memory is down — JSON is leader
                logger.warning("AgentCreator: memory mirror failed for %s: %s (JSON leader preserved)", slug, exc)

            logger.info("AgentCreator: created %s at %s", slug, target)
            return target

        except Exception:
            # Cleanup on failure: try to remove partially created folder
            if target.exists():
                try:
                    # only remove if we just created it and it has at most 2 files
                    files = list(target.iterdir())
                    if len(files) <= 3:
                        shutil.rmtree(target, ignore_errors=True)
                        # also rollback registry if we already registered
                        try:
                            self.registry.remove(slug)
                        except Exception:
                            pass
                except Exception:
                    pass
            raise

    # -- sync convenience ------------------------------------------------------

    def create_sync(
        self,
        spec: DecisionResult,
        confirm_sync: Callable[[DecisionResult], bool],
        **kwargs,
    ) -> Optional[Path]:
        """Sync wrapper for create() when you have a sync confirm callback."""

        async def _async_confirm(s: DecisionResult) -> bool:
            return confirm_sync(s)

        return asyncio.run(self.create(spec, _async_confirm, **kwargs))
